// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NokPizza.Server.Database;

#nullable disable

namespace NokPizza.Server.Migrations
{
    [DbContext(typeof(NokPizzaDbContext))]
    [Migration("20260326142111_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NokPizza.Server.Database.Models.DietaryConstraint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("DietaryConstraints");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Vegan"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Vegetarian"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Gluten"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Dairy"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Nuts"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Fish"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Shellfish"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Eggs"
                        });
                });

            modelBuilder.Entity("NokPizza.Server.Database.Models.PizzaOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("NumberOfPeople")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PizzaOrders");
                });

            modelBuilder.Entity("NokPizza.Server.Database.Models.PizzaOrderConstraints", b =>
                {
                    b.Property<Guid>("PizzaOrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ConstraintId")
                        .HasColumnType("int");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.HasKey("PizzaOrderId", "ConstraintId");

                    b.HasIndex("ConstraintId");

                    b.ToTable("PizzaOrderConstraints");
                });

            modelBuilder.Entity("NokPizza.Server.Database.Models.PizzaOrderConstraints", b =>
                {
                    b.HasOne("NokPizza.Server.Database.Models.DietaryConstraint", "DietaryConstraint")
                        .WithMany()
                        .HasForeignKey("ConstraintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NokPizza.Server.Database.Models.PizzaOrder", "PizzaOrder")
                        .WithMany("PizzaOrderConstraints")
                        .HasForeignKey("PizzaOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DietaryConstraint");

                    b.Navigation("PizzaOrder");
                });

            modelBuilder.Entity("NokPizza.Server.Database.Models.PizzaOrder", b =>
                {
                    b.Navigation("PizzaOrderConstraints");
                });
#pragma warning restore 612, 618
        }
    }
}
