// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NokPizza.Server.Database;

#nullable disable

namespace NokPizza.Server.Database.Migrations
{
    [DbContext(typeof(NokPizzaDbContext))]
    [Migration("20260329153649_AddOrderManagement")]
    partial class AddOrderManagement
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NokPizza.Server.Database.Models.DietaryConstraintModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("DietaryConstraints");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Vegan"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Vegetarian"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Gluten"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Dairy"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Nuts"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Fish"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Shellfish"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Eggs"
                        });
                });

            modelBuilder.Entity("NokPizza.Server.Database.Models.PizzaOrderModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AdminPasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("CreatorEmail")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("NormalizedCreatorEmail")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("ParticipantPasswordHash")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("RsvpDeadline")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EndTime");

                    b.HasIndex("NormalizedCreatorEmail");

                    b.HasIndex("RsvpDeadline");

                    b.ToTable("PizzaOrders");
                });

            modelBuilder.Entity("NokPizza.Server.Database.Models.PizzaOrderParticipantConstraintModel", b =>
                {
                    b.Property<Guid>("ParticipantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ConstraintId")
                        .HasColumnType("int");

                    b.HasKey("ParticipantId", "ConstraintId");

                    b.HasIndex("ConstraintId");

                    b.ToTable("PizzaOrderParticipantConstraints");
                });

            modelBuilder.Entity("NokPizza.Server.Database.Models.PizzaOrderParticipantModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<Guid>("PizzaOrderId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail");

                    b.HasIndex("PizzaOrderId", "NormalizedEmail")
                        .IsUnique();

                    b.ToTable("PizzaOrderParticipants");
                });

            modelBuilder.Entity("NokPizza.Server.Database.Models.PizzaOrderParticipantConstraintModel", b =>
                {
                    b.HasOne("NokPizza.Server.Database.Models.DietaryConstraintModel", "DietaryConstraint")
                        .WithMany()
                        .HasForeignKey("ConstraintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NokPizza.Server.Database.Models.PizzaOrderParticipantModel", "Participant")
                        .WithMany("PizzaOrderParticipantConstraints")
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DietaryConstraint");

                    b.Navigation("Participant");
                });

            modelBuilder.Entity("NokPizza.Server.Database.Models.PizzaOrderParticipantModel", b =>
                {
                    b.HasOne("NokPizza.Server.Database.Models.PizzaOrderModel", "PizzaOrder")
                        .WithMany("PizzaOrderParticipants")
                        .HasForeignKey("PizzaOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PizzaOrder");
                });

            modelBuilder.Entity("NokPizza.Server.Database.Models.PizzaOrderModel", b =>
                {
                    b.Navigation("PizzaOrderParticipants");
                });

            modelBuilder.Entity("NokPizza.Server.Database.Models.PizzaOrderParticipantModel", b =>
                {
                    b.Navigation("PizzaOrderParticipantConstraints");
                });
#pragma warning restore 612, 618
        }
    }
}
